### ISSUE TITLE
compilation error when compiled manually using gcc 

### ISSUE THREAD

**Issue by akhmed-codes** [Arsenic-ATG/Text-Editor#36]
compilation error 
```c
src/editor.c:720:9: error: a label can only be part of a statement and a declaration is not a statement
  720 |         bool save_sucess = editor_save();
```
edit: this error was produced in gcc
fixed in:- https://github.com/Arsenic-ATG/Text-Editor/pull/35

**Comment by Arsenic-ATG** [comment]
Thanks for pointing this out.
weirdly enough, my compiler fails to catch this ( even with `-Wall` )

May I know what compiler command did you gave to compile the source ?

Also what version of gcc are you using ? (`gcc -v`)

**Comment by Arsenic-ATG** [comment]
looks like you are using gcc 10.x ( or older ), because GCC dropped this after the release of GCC 11 ( In preparation of C2x ).

According to the [Release Notes](https://gcc.gnu.org/gcc-11/changes.html) 

> Several new features from the upcoming C2X revision of the ISO C standard are supported with -std=c2x and -std=gnu2x. Some of these features are also supported as extensions when compiling for older language versions. In addition to the features listed, some features previously supported as extensions and now added to the C standard are enabled by default in C2X mode and not diagnosed with -std=c2x -Wpedantic.
.....
> - Labels may appear before declarations and at the end of a compound statement.

---

Although it should be still be caught, and my compiler should have given out a warning about the same ( given the fact that I have enabled `-pedantic` in the command ). I am still investigating to why it failed to do so.

But as the project targets C99, it should be fixed.

**Comment by akhmed-codes** [comment]
Yes, I would not have noticed this error if I hadn't been using my old pc, which has `v9.3.0` installed. 
and i used `gcc -o editor src/editor.c` to compile the source
